export const TYPES = {
    AssetManager: Symbol.for("AssetManager"),
    CanvasElement: Symbol.for("CanvasElement"),
    CollisionRepository: Symbol.for("CollisionRepository"),
    CollisionBroadphaseResolver: Symbol.for("CollisionBroadphaseResolver"),
    CollisionResolutionMethod: Symbol.for("CollisionResolutionMethod"),
    CollisionAABBResolver: Symbol.for("CollisionAABBResolver"),
    CollisionCircumferenceAABBResolver: Symbol.for("CollisionCircumferenceAABBResolver"),
    CollisionCircumferenceResolver: Symbol.for("CollisionCircumferenceResolver"),
    CollisionSatResolver: Symbol.for("CollisionSatResolver"),
    CollisionMatrix: Symbol.for("CollisionMatrix"),
    EntityManager: Symbol.for("EntityManager"),
    GameConfig: Symbol.for("GameConfig"),
    InputManager: Symbol.for("InputManager"),
    LoopManager: Symbol.for("LoopManager"),
    RenderManager: Symbol.for("RenderManager"),
    SceneManager: Symbol.for("SceneManager"),
    SystemFactory: Symbol.for("SystemFactory"),
    SystemManager: Symbol.for("SystemManager"),
    TimeManager: Symbol.for("TimeManager"),
    WebGLManager: Symbol.for("WebGLManager"),
};
