name: Reusable Workflow Analyze Code

on:
    workflow_call:

jobs:
    analyze:
        name: "[Analyze Code]"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: "[Run lint]"
              run: yarn run lint

            - name: "[Run prettier-check]"
              run: yarn run prettier-check
