name: Reusable Workflow Build Code

on:
    workflow_call:

jobs:
    build:
        name: "[Build Core]"
        runs-on: ubuntu-latest
        if: contains('refs/heads/main', github.ref)
        steps:
            - uses: actions/checkout@v4

            - name: "[Restore node modules]"
              id: cache-node-modules
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: ${{ runner.os }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-nodemodules-
            - name: "[Run build]"
              run: yarn run build
