name: Continuous Integration App

on:
    - push
    - pull_request

jobs:
    Setup:
        uses: ./.github/workflows/setupNode.yml

    Analyze:
        needs: Setup
        uses: ./.github/workflows/analyzeCode.yml

    Build:
        needs: [Setup, Analyze]
        uses: ./.github/workflows/buildCode.yml
